# Generated by Django 4.1.3 on 2022-11-27 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='party name')),
                ('password', models.CharField(max_length=30, unique=True, verbose_name='password')),
                ('join_deadline', models.DateField(verbose_name='deadline to join')),
                ('exchange_date', models.DateField(verbose_name='date of gift exchange')),
                ('spending_limit', models.SmallIntegerField(verbose_name='spending limit')),
                ('landing_message', models.TextField(blank=True, verbose_name='message on party landing page')),
            ],
        ),
        migrations.CreateModel(
            name='Santa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email_address', models.EmailField(max_length=60)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.party')),
                ('recipient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifter', to='groups.santa')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'party'), ('email_address', 'party')},
            },
        ),
    ]
